services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5437:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: